version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    # Overrides default command, replace with the command to start your Flask app
    command: python /workspace/app.py  # Chạy file app.py hoặc file chính của Flask
    ports:
      - "8000:8000"  # Xuất cổng 8000 của app ra bên ngoài container
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    networks:
      - app-network

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
